name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
            go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - run: go build -a -o release/demo-k8s
      
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: github.com/as-polyakov/k8s-demo

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
